# Generated by Django 4.0.3 on 2022-04-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date',
            field=models.CharField(default=1651255317558, max_length=140),
            preserve_default=False,
        ),
    ]
