# Generated by Django 4.0.3 on 2022-04-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0005_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(default=1651321985299, upload_to='', verbose_name='images/'),
            preserve_default=False,
        ),
    ]
