# Generated by Django 4.0.3 on 2022-04-30 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0009_alter_student_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
    ]
